# docker-compose.yml
version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: docker-server/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./keywordExtractAPI:/srv/docker-server
          - ./log:/var/log/nginx
        depends_on:
          - django

    django:
        container_name: keywordextract
        build: ./keywordExtractAPI
        image: docker-server/keywordextract
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./keywordExtractAPI:/srv/docker-server
          - ./log:/var/log/uwsgi

    crawler:
        container_name: crawling
        build: ./crawlingAPI
        ports:
          - "8000:8000"
        image: docker-server/crawling
        restart: always
        command: "python manage.py runserver 0.0.0.0:8000"
        depends_on:
          - django