# Generated by Django 4.1.2 on 2022-10-30 22:28

import crawling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawlingmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=50)),
                ('hashtag', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SaveImageModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=crawling.models.upload_to)),
            ],
        ),
    ]
